### ISSUE TITLE
Customized sorting CommitGroups not working?

### ISSUE THREAD

**Issue by maicol07** [git-chglog/git-chglog#140]
## Expected Behavior
Commit groups sorted as I have specified in the options

## Actual Behavior
Commit groups are not sorted

## Steps to Reproduce (including precondition)
1. Use the following options in your config file:
```yaml
commit_groups:
    sort_by: Custom
    title_order:
        - feat
        - update
        - perf
        - fix
        - refactor
        - build
        - chore
    title_maps:
        feat: ✨ Features
        fix: 🐛 Bug Fixes
        perf: ⚡ Performance Improvements
        refactor: ♻ Code Refactoring
        update: 🔄 Updates
        build: 👷 Building scripts changes
        chore: Other changes
```
2. Generate the changelog

## Your Environment
- OS: Windows 10
- git-chglog version: 0.14
