### ISSUE TITLE
Docs: Clarify how to exclude commit messages with specific commit metadata

### ISSUE THREAD

**Issue by tommyalatalo** [git-chglog/git-chglog#146]
I'm trying to figure out how to exclude certain commit messages from my changelog, but the documentation isn't clear about how to do so.

Specifically I want to skip adding `chore(release):` commits to the changelog, as those are made redundant by the markdown headers that already contain the same information. How to exclude commits of a specific type and scope isn't quite clear from the docs, there is no example for how to do it. Do you need pattern matching for this?

I tried the in order to exclude all commits of chore type and release scope (with OR), but no success.
Is there any way implemented to do blacklisting of commits with `AND` conditionals, or just pattern matching like `^chore(release)`? 
```
options
  commits:
    filters:
      Type:
        - "^chore"
      Scope:
        - "^release"
```
