### ISSUE TITLE
Docs: Examples for filtering commits out

### ISSUE THREAD

**Issue by wrrrn** [git-chglog/git-chglog#26]
I'm looking to create a filter which ignores commits matching a certain string. The goal is to ignore the actual changelog commit to the repo, so our header string will be `Updated changelog`.

I feel like I'm missing something obvious. Could someone point me in the right direction?

## Expected Behavior

```
filters:
  pattern:
    - "String causing commit to be ignored. ie - Updated changelog"
  pattern_maps:
    - Header
```

## Actual Behavior

Nada
 

## Your Environment

- OS: {Please write here}
- git-chglog version: 0.7.0
