### ISSUE TITLE
Add support for multiple Types per title

### ISSUE THREAD

**Issue by ironsalsa** [git-chglog/git-chglog#33]
Add support for multiple Types to get grouped together, so my devs can use their own preferred type selector and still generate the same changelog.

## Expected Behavior
Ability to let my devs use both "feat:" and "feature:" while grouping them together in the changelog by Title from the title_maps.

## Actual Behavior
Every type shows up in a different heading, even though the types that ought to be grouped are mapped to a string exactly the same as others.

## Steps to Reproduce (including precondition)
Add Types that you want to group in the same heading, and look for a way to do that. Find nothing because the logic doesn't allow for it.
{Please write here}

## Your Environment

- OS: Ubuntu 18.04
- git-chglog version: 0.7.1

I understand the solution from the author's perspective would be to force the devs to standardize their Type tags, but I would prefer to offer my team the flexibility to not remember "bug:" and "bugfix:" don't do the same thing in the changelog.

If I have time on this project (haha that's a good one) I'll attempt to add error checking into the md template to group exact matches together. It seems like it wouldn't be hard to change the type on the commit_groups.title_maps to accept an array/slice of strings instead of a single string to the match. Might make sense to do a bigger refactor and set commits.filters.type to be an array of string([]string) maps with the desired heading titles as the keys and an array of possible type matches as the values. 

Let me know if this is a worthwhile update - if my devs rebel too much, I may fork and implement one of these options, but that would be a refactoring project for sure.

**Comment by ironsalsa** [comment]
Also, thanks for all the great work on this project! This is the best way to automate change logs across multi language projects without littering package.json all over non-JS repos.

**Comment by tami5** [comment]
👍 I found my self looking for such a thing, it would be nice to have that. I tried the following but it's seems to have created multiple sections

```yaml
    title_maps:
      sparkles: ":sparkles: Features"
      bug: ":bug: Bug Fixes"
      ambulance: ":bug: Bug Fixes"
      adhesive_bandage: ":bug: Bug Fixes"
      zap: ":zap: Performance Improvements"
      recycle: ":recycle: Code Refactoring"
      fire: ":recycle: Code Refactoring"
      truck: ":recycle: Code Refactoring"
      art: ":art: Improve structure / format of the code."
      memo: ":memo: Add or update documentation."
      white_check_mark: ":white_check_mark: Add/Update Test Cases"
      package: ":package: Dependencies"
      lock: ":lock: Security"
      construction_worker: ":construction_worker: CI Updates"

```

**Comment by rshmhrj** [comment]
+1

I was looking for a way to add a regex to the title map, e.g.:

```yml
[Aa]dd(?:s|ed|ing): Features
[Cc]hang(?:e|es|ed|ing): Features
[Ff]ea(?:t|ture|tures|turing): Features
sparkles: Features
```

and have all of those variates map to the same `Features` section within the Changelog.

**Comment by rshmhrj** [comment]
Hi @ironsalsa @kkharji 

Here is an almost fully working workaround.
It uses the go template itself to copy same named commit groups together.

Entire `.chglog/CHANGELOG.tpl.md` file
```md
{{ range .Versions }}
<a name="{{ .Tag.Name }}"></a>
## {{ if .Tag.Previous }}[{{ .Tag.Name }}]({{ $.Info.RepositoryURL }}/compare/{{ .Tag.Previous.Name }}...{{ .Tag.Name }}){{ else }}{{ .Tag.Name }}{{ end }}

> {{ datetime "2006-01-02" .Tag.Date }}

{{ $rawCG := .CommitGroups }}{{ $mergedCG := dict -}}{{- $mergedTitles := dict -}}{{- range $cg := $rawCG -}}{{- $title := .Title -}}{{- if not (hasKey $mergedCG $title) -}}{{- $tmp := dict -}}{{- and (set $tmp "title" $title) (set $tmp "commits" .Commits) (set $mergedCG $title $tmp) -}}{{- else -}}{{- $mcg := (get $mergedCG $title) -}}{{- $mc := $mcg.commits -}}{{- $allCommits := $mc -}}{{- range .Commits -}}{{- $allCommits = append $allCommits . -}}{{- end -}}{{- $tmp := dict -}}{{- and (set $tmp "title" $title) (set $tmp "commits" $allCommits) (set $mergedCG $title $tmp) -}}{{- end -}}{{- end }}

{{ range $mergedCG }}
### {{ .title }}

{{ range .commits -}}
* {{ .Subject }}
{{ end }}
{{ end -}}
{{ end -}}
```

Here is a portion of the `options.commit_groups.title_maps` from `config.yml`
```yml
...
options:
  commit_groups:
    title_maps:
      ...
      bug: Fixed 🐛
      Bug: Fixed 🐛
      fix: Fixed 🐛
      fixing: Fixed 🐛
      pencil2: Fixed 🐛
      Pencil2: Fixed 🐛
      meta: Fixed 🐛
      minor: Fixed 🐛
      typo: Fixed 🐛
      ambulance: Fixed 🐛
      Ambulance: Fixed 🐛
      lock: Fixed 🐛
      Lock: Fixed 🐛
```

The result is a set of grouped commits:
![image](https://github.com/git-chglog/git-chglog/assets/750874/22e27559-8757-40bc-9670-ced88450d345)

The only caveat is that there is now some additional data printed at the top of each section where the calculations are being done.  I can't figure out how to get it to **_NOT_** render.  I removed as much whitespace as possible, tried various ways to comment it out, but it's still there.

![image](https://github.com/git-chglog/git-chglog/assets/750874/04ad4068-df5c-43f7-af51-e8661c488cff)

IMO, it's much easier to remove this single line than try to merge all the CommitGroup sections together by hand.

Also, one last tweak I made to the header pattern that you might be interested in:
```yaml
options:
  ...
  header:
    pattern: "^:+(🚑️|💥|✨|🔥|🔒️|⬆️|⬇️|🐛|👷|🔧|📝|🙈|⚡️|✅|♻️|🔀|🚧|🔖+ +\\w+|\\w+)*:+!?\\(?\\w*\\)?:?\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
```

This captures commits in all sorts of non-standardized formats:
![image](https://github.com/git-chglog/git-chglog/assets/750874/7ad3b70b-2499-4f5f-9240-c224f6cb6285)
