### ISSUE TITLE
wishlist: New sort_by type for commit groups

### ISSUE THREAD

**Issue by khos2ow** [git-chglog/git-chglog#60]
## Expected Behavior

This is more of a general question rather than actual bug report.

Considering the following config:

```yaml
...
  commit_groups:
    title_maps:
      doc: Documentation
      enhance: Enhancements
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
...
```

This will generate changelog with separated commit groups sorted by *group title*. The only available sort option, based on [this](https://github.com/git-chglog/git-chglog#optionscommit_groups) is by `Title`.

In reality some of the items might have higher logical priority in the log, for example I like to show `Features` first and then `Enhancements` before `Bug Fixes` and so on. So I was wondering if there was ever a decision to implement something like `sort_by: Position` which retains the order of item in title maps, that one can do something like this:

```yaml
...
  commit_groups:
    sort_by: Position
    title_maps:
      feat: Features
      enhance: Enhancements
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      doc: Documentation
...
```

I'd appreciate any feedback on this, and also wanted to point out I can help with any potential PR if this is actually considered to get implemented.

## Actual Behavior

n/a

## Steps to Reproduce (including precondition)

n/a

## Screenshot on This Problem (if possible)

n/a

## Your Environment

- OS: `Linux 5.0.0-37-generic`
- git-chglog version: `git-chglog version 0.9.1`

**Comment by wadackel** [comment]
Hi @khos2ow, Thank you for sending the issue! And I'm sorry too late response... :cry:
I think this is a very good feature. If you are still willing to send me a PR, I would be very happy :)

**Comment by khos2ow** [comment]
Thank you @wadackel , I sent a PR for this.

**Comment by khos2ow** [comment]
For future reader of the issue, the proposed change in #69 is as follows:

```yaml
options:
  ...
  commit_groups:
    sort_by: Custom <-- required keyword 
    title_order:    <-- predefined ordered list of titles to apply sort with 
      - feat
      - fix
      - enhance
      - refactor
      - perf
      - docs
    title_maps:
      docs: Documentation
      enhance: Enhancements
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
  ...
```
