### ISSUE TITLE
Git-chglog installation via go fails

### ISSUE THREAD

**Issue by RymRabehi** [git-chglog/git-chglog#88]
## Expected Behavior

`go get -u github.com/git-chglog/git-chglog/cmd/git-chglog`
=> install git-chglog

## Actual Behavior

```
# github.com/git-chglog/git-chglog/cmd/git-chglog
go/src/github.com/git-chglog/git-chglog/cmd/git-chglog/main.go:74:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/git-chglog/git-chglog/cmd/git-chglog/main.go:80:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/git-chglog/git-chglog/cmd/git-chglog/main.go:87:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/git-chglog/git-chglog/cmd/git-chglog/main.go:92:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/git-chglog/git-chglog/cmd/git-chglog/main.go:98:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/git-chglog/git-chglog/cmd/git-chglog/main.go:104:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/git-chglog/git-chglog/cmd/git-chglog/main.go:107:4: unknown field 'EnvVar' in struct literal of type cli.BoolFlag
go/src/github.com/git-chglog/git-chglog/cmd/git-chglog/main.go:111:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/git-chglog/git-chglog/cmd/git-chglog/main.go:114:4: unknown field 'EnvVar' in struct literal of type cli.BoolFlag
go/src/github.com/git-chglog/git-chglog/cmd/git-chglog/main.go:118:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/git-chglog/git-chglog/cmd/git-chglog/main.go:118:15: too many errors
```

## Steps to Reproduce (including precondition)

Run `go get -u github.com/git-chglog/git-chglog/cmd/git-chglog`

## Screenshot on This Problem (if possible)

![git-chglog](https://user-images.githubusercontent.com/15215518/104622130-27a05e00-5691-11eb-9d99-6e4c21b9fca0.png)

## Your Environment

- OS: Debian 10.5
- git-chglog version: n/a
- go version : 1.15.6

**Comment by mavogel** [comment]
Weird. Got the same errors running `GO111MODULE=off go get -u github.com/git-chglog/git-chglog/cmd/git-chglog` as you described. Whereas `make build` works on `master` and furthermore the `go get ...` fails it installs it correctly in `$GOBIN` 🤔
```
GO111MODULE=off go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
... <errors like above>
$ git-chglog --version  
git-chglog version 0.9.1
$ which git-chglog
/Users/mavogel/go/bin/git-chglog
```

**Comment by davidovich** [comment]
I believe the problem is caused by the `-u` switch which is not something you generally want. In modern go, `-u` will try to update all transitive dependencies of the current package to their latest version, which is a developper level command, not a user level one (the user should just install what the developer intended, not do an upgrade at the same time).

Also, the command is in constant evolution and changes from go release to go release.  See the wiki for information on [releases](https://github.com/golang/go/wiki/Modules#recent-changes). In the upcoming go 1.16, the equivalent command of installing a binary will be `go install`.

The same command works for me without the `-u`. (on go 1.15).

```bash
# make sure to run this outside a repo which contains a go.mod, as go will want to update go.mod
cd; GO111MODULE=on go get github.com/git-chglog/git-chglog/cmd/git-chglog
```

One note. The go tags should be preceded with the `v` prefix to be a valid module. Otherwise, upon install we get versions looking like this: `v0.0.0-20210110144858-d6315435a3ac` which is a pseudo-version. If you change the tag format to include the `v` prefix, you would get: `v0.9.1` as expected.

**Comment by mavogel** [comment]
Thanks @davidovich for the explanations. 

> One note. The go tags should be preceded with the v prefix to be a valid module

Yes we will consider this when switching to the new release process in #58

**Comment by Yaakoi** [comment]
Hi, we had the same error and it seems that this is due to the last update of the repo.
So our solution was to use the previous release and it works !

To use it :
1. you have to initialize yourself your _/github.com_ directory
2. Initialize go mod in this directory
3. Run `go get` command with the release you want to use

Check the following code; we run it using gitlab CI/CD configuration file in a docker container using golang image :
 
```
bump version:
  stage: release
  image: golang:latest

  variables:
    GIT_STRATEGY: clone

  before_script:
    - *ssh_add
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"

  script:
    - echo "--> ${CI_COMMIT_REF_NAME}"
    - *get_version
    - echo "Prepare bump release ${NEW_VERSION}"
    - mkdir -p /go/src/github.com
    - (cd /go/src/github.com ; go mod init ; go get -v github.com/git-chglog/git-chglog/cmd/git-chglog@0.9.1)
    - *bump

  when: manual
  allow_failure: false

  only:
    - master

  except:
    refs:
      - tags
      - merge_requests
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release\)*/
      - $CI_COMMIT_MESSAGE =~ /^doc\(*/

  artifacts:
    paths:
      - CHANGELOG.md

  cache: {}
```

The only thing we changed is in `script`, we have replaced 
`go get -u github.com/git-chglog/git-chglog/cmd/git-chglog`
with
```
    - mkdir -p /go/src/github.com
    - (cd /go/src/github.com ; go mod init ; go get -v github.com/git-chglog/git-chglog/cmd/git-chglog@0.9.1)
```

Hope this help !
