### ISSUE TITLE
Merges rex on multiline commits

### ISSUE THREAD

**Issue by anthonymq** [git-chglog/git-chglog#91]
Hi,
When I try to write a regex to capture the Gitlab Merge Request number in the "merges" section of the configuration, I don't capture anything.
Is it possible to right a multiline regex ?

## Expected Behavior
Example Merge commit from Gitlab:
```
Date:   Mon Jan 25 16:17:25 2021 +0000
    Merge branch 'feature/XXX-11111' into 'master'

    XXX-11111 - Example

    See merge request myproject/frontend!1234
```

Config: 
```
options:
  tag_filter_pattern: '^\d+\.\d+\.\d+$'
  merges:
    pattern: "(!\\d+)"
    pattern_maps:
      - Source
```

## Actual Behavior

It doesn't put anything in the "Source" field
